[package]
name = "loader"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
hex = "0.4.3"
winapi = {version="0.3.9",features=["winuser","memoryapi","errhandlingapi"]}
